version: '3.8'

services:
  repository-manager:
    image: edissonz8809/ia-ops-repository-manager:latest
    container_name: iaops-repository-manager
    restart: unless-stopped
    ports:
      - "${REPOSITORY_MANAGER_PORT:-8860}:8850"
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@host.docker.internal:5434/iaops}
      - REDIS_URL=${REDIS_URL:-redis://host.docker.internal:6380/0}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT:-host.docker.internal:9898}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-minioadmin123}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - dev-core-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8850/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  task-manager:
    image: edissonz8809/ia-ops-task-manager:latest
    container_name: iaops-task-manager
    restart: unless-stopped
    ports:
      - "${TASK_MANAGER_PORT:-8861}:8851"
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@host.docker.internal:5434/iaops}
      - REDIS_URL=${REDIS_URL:-redis://host.docker.internal:6380/0}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT:-host.docker.internal:9898}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-minioadmin123}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - dev-core-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8851/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  log-manager:
    image: edissonz8809/ia-ops-log-manager:latest
    container_name: iaops-log-manager
    restart: unless-stopped
    ports:
      - "${LOG_MANAGER_PORT:-8862}:8852"
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@host.docker.internal:5434/iaops}
      - REDIS_URL=${REDIS_URL:-redis://host.docker.internal:6380/0}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - dev-core-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8852/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  datasync-manager:
    image: edissonz8809/ia-ops-datasync-manager:latest
    container_name: iaops-datasync-manager
    restart: unless-stopped
    ports:
      - "${DATASYNC_MANAGER_PORT:-8863}:8863"
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@host.docker.internal:5434/iaops}
      - REDIS_URL=${REDIS_URL:-redis://host.docker.internal:6380/0}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT:-host.docker.internal:9898}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-minioadmin123}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - dev-core-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8863/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  github-runner-manager:
    image: edissonz8809/ia-ops-github-runner:latest
    container_name: iaops-github-runner-manager
    restart: unless-stopped
    ports:
      - "${GITHUB_RUNNER_MANAGER_PORT:-8864}:8864"
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@host.docker.internal:5434/iaops}
      - REDIS_URL=${REDIS_URL:-redis://host.docker.internal:6380/0}
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
      - GITHUB_REPO=${GITHUB_REPO:-giovanemere/ia-ops}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - dev-core-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8864/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  techdocs-builder-manager:
    image: edissonz8809/ia-ops-techdocs-builder:latest
    container_name: iaops-techdocs-builder-manager
    restart: unless-stopped
    ports:
      - "${TECHDOCS_BUILDER_MANAGER_PORT:-8865}:8865"
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@host.docker.internal:5434/iaops}
      - REDIS_URL=${REDIS_URL:-redis://host.docker.internal:6380/0}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - dev-core-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8865/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Provider Administration API
  provider-admin:
    image: edissonz8809/ia-ops-provider-admin:2.0.0
    container_name: iaops-provider-admin
    restart: unless-stopped
    ports:
      - "${PROVIDER_ADMIN_PORT:-8866}:8866"
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@host.docker.internal:5434/iaops}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:-your-encryption-key-here}
      - PROVIDER_ADMIN_SECRET=${PROVIDER_ADMIN_SECRET:-admin-secret}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8866/api/v1/health/"]
      interval: 30s
      timeout: 10s
      retries: 3

  swagger-portal:
    image: edissonz8809/ia-ops-swagger-portal:latest
    container_name: iaops-swagger-portal
    restart: unless-stopped
    ports:
      - "${SWAGGER_PORTAL_PORT:-8870}:8870"
    environment:
      - REPOSITORY_MANAGER_URL=http://iaops-repository-manager:8850
      - TASK_MANAGER_URL=http://iaops-task-manager:8851
      - LOG_MANAGER_URL=http://iaops-log-manager:8852
      - DATASYNC_MANAGER_URL=http://iaops-datasync-manager:8863
      - GITHUB_RUNNER_MANAGER_URL=http://iaops-github-runner-manager:8864
      - TECHDOCS_BUILDER_URL=http://iaops-techdocs-builder-manager:8865
    networks:
      - dev-core-network
    depends_on:
      - repository-manager
      - task-manager
      - log-manager
      - datasync-manager
      - github-runner-manager
      - techdocs-builder-manager
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8870/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  testing-portal:
    image: edissonz8809/ia-ops-testing-portal:latest
    container_name: iaops-testing-portal
    restart: unless-stopped
    ports:
      - "18860:18860"
      - "18861:18861"
      - "18862:18862"
    volumes:
      - ./test-results:/app/test-results
    networks:
      - dev-core-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:18860/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  dev-core-network:
    driver: bridge
    name: iaops-dev-core-network
