site_name: IA-Ops Dev Core Services
site_description: Ecosistema completo de desarrollo para IA-Ops con Service Layer unificado
site_author: IA-Ops Team
site_url: https://ia-ops-dev-core.docs

# Repository
repo_name: giovanemere/ia-ops-dev-core
repo_url: https://github.com/giovanemere/ia-ops-dev-core

# Configuration
theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

# Navigation
nav:
  - Home: index.md
  - Architecture:
    - Service Layer: architecture/service-layer.md
    - Infrastructure: architecture/infrastructure.md
    - Integration: architecture/integration.md
  - API Documentation:
    - Overview: api/overview.md
    - Endpoints: api/endpoints.md
    - Authentication: api/authentication.md
  - Providers:
    - Configuration: providers/configuration.md
    - GitHub: providers/github.md
    - Azure: providers/azure.md
    - AWS: providers/aws.md
    - GCP: providers/gcp.md
    - OpenAI: providers/openai.md
  - Development:
    - Getting Started: development/getting-started.md
    - Testing: development/testing.md
    - Deployment: development/deployment.md
  - User Stories: user-stories.md

# Plugins
plugins:
  - search
  - mermaid2

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/giovanemere/ia-ops-dev-core
  version:
    provider: mike
