version: '3.8'

services:
  repository-manager:
    build:
      context: ../api
      dockerfile: Dockerfile.repository
    container_name: iaops-repository-manager
    restart: unless-stopped
    ports:
      - "${REPOSITORY_MANAGER_PORT:-8860}:8850"
    environment:
      - MINIO_ENDPOINT=${MINIO_ENDPOINT:-localhost:9898}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-minioadmin123}
    volumes:
      - ../data:/app/data
      - ../logs:/app/logs
    networks:
      - dev-core-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8850/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  task-manager:
    build:
      context: ../api
      dockerfile: Dockerfile.task
    container_name: iaops-task-manager
    restart: unless-stopped
    ports:
      - "${TASK_MANAGER_PORT:-8861}:8851"
    environment:
      - MINIO_ENDPOINT=${MINIO_ENDPOINT:-localhost:9898}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-minioadmin123}
    volumes:
      - ../data:/app/data
      - ../logs:/app/logs
    networks:
      - dev-core-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8851/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  log-manager:
    build:
      context: ../api
      dockerfile: Dockerfile.log
    container_name: iaops-log-manager
    restart: unless-stopped
    ports:
      - "${LOG_MANAGER_PORT:-8862}:8852"
    volumes:
      - ../data:/app/data
      - ../logs:/app/logs
      - /home/giovanemere/ia-ops/ia-ops-docs/logs:/app/logs:ro
    networks:
      - dev-core-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8852/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  dev-core-network:
    driver: bridge
    name: iaops-dev-core-network
